CREATE TABLE IF NOT EXISTS secrets  (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `secret_key` VARCHAR(255) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);